module.exports = {
  RECEIVE_ALL_MEMBERSHIPS: "RECEIVE_ALL_MEMBERSHIPS",
  RECEIVE_ONE_MEMBERSHIP: "RECEIVE_ONE_MEMBERSHIP",
  REMOVE_ONE_MEMBERSHIP: "REMOVE_ONE_MEMBERSHIP",
  ADD_ONE_MEMBERSHIP: "ADD_ONE_MEMBERSHIP"
};
