module.exports = {
  RECEIVE_NAV_RESOURCES: "RECEIVE_NAV_RESOURCES",
  RECEIVE_TODOS: "RECEIVE_TODOS",
  RECEIVE_EVENTS: "RECEIVE_EVENTS",
  RECEIVE_MESSAGES: "RECEIVE_MESSAGES",
  RECEIVE_ONE_RESOURCE: "RECEIVE_ONE_RESOURCE",
  EVENTS: "EVENTS",
  TODOS: "TODOS",
  TODOLISTS: "TODOLISTS",
  MESSAGES: "MESSAGES",
  UPLOADS: "UPLOADS",
  PROJECTS: "PROJECTS"
};
