module.exports = {
  RECEIVE_TODOS: "RECEIVE_TODOS",
  RECEIVE_ONE_TODO: "RECEIVE_ONE_TODO",
  ADD_ONE_TODO: "ADD_ONE_TODO",
  DELETE_ONE_TODO: "DELETE_ONE_TODO",

  RECEIVE_ONE_TODO_LIST: "RECEIVE_ONE_TODO_LIST"
};
