module.exports = {
  RECEIVE_TODOS: "RECEIVE_TODOS",
  RECEIVE_ONE_TODO: "RECEIVE_ONE_TODO",
  ADD_ONE_TODO: "ADD_ONE_TODO",
  DELETE_ONE_TODO: "DELETE_ONE_TODO",

  RECEIVE_ONE_TODO_LIST: "RECEIVE_ONE_TODO_LIST",
  REMOVE_TODO_LIST: "REMOVE_TODO_LIST",

  // Pusher Constants
  CREATE_TODO: "CREATE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  DESTROY_TODO: "DESTROY_TODO",

  CREATE_TODO_LIST: "CREATE_TODO_LIST",
  UPDATE_TODO_LIST: "UPDATE_TODO_LIST",
  DESTROY_TODO_LIST: "DESTROY_TODO_LIST"
};
